// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern int backsub (
hls::stream<struct ap_axiu<32, 1, 1, 1 > >& inStream,
hls::stream<struct ap_axiu<8, 1, 1, 1 > >& outStream,
unsigned short frame[76800],
bool init);
